# Just, output
Ranking #206 as of 2/3

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Columns: 288 entries, row_id to target
dtypes: float64(286), int64(1), object(1)
memory usage: 439.5+ MB

In [3]:
from pycaret.classification import *
df2 = train_df.sample(n=50000)

In [4]:
exp1 = setup(df2, target = 'target')

In [5]:
compare_models()

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=974, verbose=0,
                     warm_start=False)

In [6]:
rf = create_model('et')

In [7]:
evaluate_model(rf)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [8]:
tuned_rf = tune_model(rf)

In [9]:
final_rf = finalize_model(rf)
print(final_rf)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=974, verbose=0,
                     warm_start=False)

In [10]:
#予測の実行
unseen_predictions = predict_model(final_rf, data = test_df)

In [15]:
print(unseen_predictions)

       row_id     A0T0G0C10  A0T0G1C9      A0T0G2C8  A0T0G3C7  A0T0G4C6  \
0      200000 -9.536743e-07 -0.000002 -9.153442e-07  0.000024  0.000034
1      200001 -9.536743e-07 -0.000010 -4.291534e-05 -0.000114  0.001800
2      200002  4.632568e-08  0.000003  8.465576e-08 -0.000014  0.000007
3      200003 -9.536743e-07 -0.000008  8.084656e-06  0.000216  0.000420
4      200004 -9.536743e-07 -0.000010 -4.291534e-05 -0.000114 -0.000200
...       ...           ...       ...           ...       ...       ...
99995  299995 -9.536743e-07 -0.000008 -4.291534e-05 -0.000108 -0.000194
99996  299996 -9.536743e-07 -0.000010 -4.291534e-05 -0.000114 -0.000200
99997  299997 -9.536743e-07 -0.000010 -4.291534e-05 -0.000114 -0.000200
99998  299998 -9.536743e-07 -0.000010 -4.291534e-05 -0.000114 -0.000200
99999  299999 -9.536743e-07 -0.000009 -3.991534e-05 -0.000111 -0.000195

       A0T0G5C5  A0T0G6C4  A0T0G7C3  A0T0G8C2  ...  A8T0G2C0  A8T1G0C1  \
0     -0.000002  0.000021  0.000024 -0.000009  ...  0.000055  0.000108
1     -0.000240  0.001800 -0.000114  0.000957  ... -0.000043 -0.000086
2     -0.000005 -0.000004  0.000003  0.000004  ...  0.000084  0.000111
3      0.000514  0.000452  0.000187 -0.000005  ...  0.000098  0.000175
4     -0.000240 -0.000200 -0.000114 -0.000043  ... -0.000043 -0.000086
...         ...       ...       ...       ...  ...       ...       ...
99995 -0.000234 -0.000195 -0.000110 -0.000043  ...  0.000489  0.000499
99996 -0.000240 -0.000200 -0.000114 -0.000043  ... -0.000043 -0.000086
99997 -0.000240 -0.000200 -0.000114 -0.000043  ... -0.000043  0.000914
99998 -0.000240 -0.000200 -0.000114 -0.000043  ... -0.000043 -0.000086
99999 -0.000238 -0.000189 -0.000110 -0.000042  ...  0.000424  0.000834

       A8T1G1C0  A8T2G0C0  A9T0G0C1  A9T0G1C0  A9T1G0C0     A10T0G0C0  \
0      0.000090  0.000059  0.000010  0.000006  0.000027  4.632568e-08
1     -0.000086 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07
2      0.000117  0.000070  0.000020  0.000030  0.000021  4.632568e-08
3      0.000217  0.000150  0.000018  0.000016  0.000051 -9.536743e-07
4      0.000914 -0.000043 -0.000010 -0.000010  0.000990 -9.536743e-07
...         ...       ...       ...       ...       ...           ...
99995  0.000899  0.000443  0.000047  0.000148  0.000101  4.046326e-06
99996 -0.000086 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07
99997 -0.000086 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07
99998 -0.000086 -0.000043 -0.000010 -0.000010 -0.000010 -9.536743e-07
99999  0.000875  0.000485  0.000128  0.000144  0.000148  2.046326e-06

                          Label   Score
0        Escherichia_fergusonii  0.9999
1           Salmonella_enterica  0.7666
2            Enterococcus_hirae  0.9805
3           Salmonella_enterica  1.0000
4         Staphylococcus_aureus  0.9351
...                         ...     ...
99995  Streptococcus_pneumoniae  1.0000
99996          Escherichia_coli  0.3301
99997       Salmonella_enterica  0.6910
99998      Bacteroides_fragilis  0.8156
99999    Streptococcus_pyogenes  0.9999

[100000 rows x 289 columns]

In [11]:
unseen_predictions = unseen_predictions.rename(columns={'Label': 'target'})

In [12]:
submit = unseen_predictions.filter(items=['row_id', 'target'])

In [13]:
submit

       row_id                    target
0      200000    Escherichia_fergusonii
1      200001       Salmonella_enterica
2      200002        Enterococcus_hirae
3      200003       Salmonella_enterica
4      200004     Staphylococcus_aureus
...       ...                       ...
99995  299995  Streptococcus_pneumoniae
99996  299996      Bacteroides_fragilis
99997  299997      Bacteroides_fragilis
99998  299998      Bacteroides_fragilis
99999  299999    Streptococcus_pyogenes

[100000 rows x 2 columns]

In [15]:
submit.to_csv('submit0204.csv',index=False)